### ISSUE TITLE
[QUESTION] Any way to prevent duplicates while simple matching?

### ISSUE THREAD

**Issue by maulberto3** [sb-ai-lab/HypEx#122]
Hi, awesome library. 

I see that when using Matcher, the matched df still holds the same length. 

I checked and it seems that some samples got matched more than once. 

So any way to prevent this i.e. match R' MatchIt approach?

**Comment by tikhomirovd** [comment]
Hi! Thank you for your interest in our library.

Yes, we have functionality that allows you to prevent samples from being matched more than once. This is detailed in our [notebook on unique matching](https://github.com/sb-ai-lab/HypEx/blob/master/examples/tutorials/Matching%20without%20replacement.ipynb).

Please note that this method may not be as fast as the standard matching because FAISS doesn’t support searching without repeats out of the box. We had to implement a workaround that might slow down the process.

However, in many matching tasks, having repeats isn’t usually a significant issue. Often, some samples naturally serve as common matches—think of them as “average” clients that are representative of multiple cases.

Let us know if you have any more questions!
